# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: 0.0.1.{build}
skip_tags: true
image: Visual Studio 2017
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  NugetApiKey:
    secure: 3sC7bUSY534F4WnpYXlP7XyikulxbSpfLZgC3y37gA2OAeMp35la0zplVjiliOFn
  ModuleName: BetterTls

build: false

test_script:
  - ps: . .\build.ps1
